# Generated by Django 4.2 on 2023-04-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_categories_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
